#baseURL = "http://localhost:1313/"
baseURL = "https://sgo.cool"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "思°"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 8                       # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "VarKai"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "文章"
  weight = 20
  identifier = "Archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "思危 , 思变 , 思退"                                       # site's subTitle  # 网站二级标题
  footerSlogan = " 路漫漫其修远兮，吾将上下而求索 "                    # site's footer slogan  # 网站页脚标语
  keywords = ["思考","技术","编程","架构","管理","商业"]                                  # site's keywords  # 网站关键字
  description = "思考: 如何才能在高效的管理下，运用简洁的架构，驱动优雅地编程，实现商业的可持续化." # site's description  # 网站描述
  enableMathJax = true                                                # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/gokins"
 #twitter = " "
 #facebook = " "
  weibo = "https://weibo.com/aiwanfulishe"
 #instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
